gke_clusters:
  primary_cluster:
    name: zena-primary
    location: us-west4
    type: private
    version: "1.27"
    networking:
      network: zena-vpc
      subnet: gke-subnet-west4
      pod_range: 10.0.0.0/14
      service_range: 10.4.0.0/19
    node_pools:
      - name: zena-general
        machine_type: n1-standard-4
        min_nodes: 3
        max_nodes: 10
        autoscaling: enabled
      - name: ray-workers
        machine_type: n1-standard-16
        min_nodes: 2
        max_nodes: 8
        autoscaling: enabled
        labels:
          ray.io/node-type: worker
      - name: ml-workers
        machine_type: n2-standard-16
        accelerator:
          type: nvidia-tesla-t4
          count: 1
        min_nodes: 2
        max_nodes: 6

  secondary_cluster:
    name: zena-secondary
    location: us-west1
    type: private
    version: "1.27"
    networking:
      network: zena-vpc
      subnet: gke-subnet-west1
      pod_range: 10.8.0.0/14
      service_range: 10.12.0.0/19
    node_pools:
      - name: deepmind-workers
        machine_type: n1-standard-16
        min_nodes: 2
        max_nodes: 6
        labels:
          workload: deepmind

ray_config:
  primary_cluster:
    name: ray-west4
    namespace: ray-system
    head_service:
      cpu: 8
      memory: 32Gi
    worker_groups:
      - name: general-workers
        replicas: 3
        min_replicas: 2
        max_replicas: 8
        cpu: 8
        memory: 16Gi
      - name: gpu-workers
        replicas: 2
        min_replicas: 1
        max_replicas: 4
        cpu: 8
        memory: 32Gi
        gpu: 1
    autoscaling:
      enabled: true
      target_cpu_utilization: 75

  secondary_cluster:
    name: ray-west1
    namespace: ray-system
    head_service:
      cpu: 8
      memory: 32Gi
    worker_groups:
      - name: deepmind-workers
        replicas: 2
        min_replicas: 1
        max_replicas: 4
        cpu: 16
        memory: 64Gi