secrets_management:
  secret_manager:
    locations:
      - us-west4
      - us-west1
    replication_policy: automatic
    secrets:
      auth:
        - name: "claude-api-key"
          version_labels: ["prod", "stage"]
        - name: "deepmind-auth-token"
          version_labels: ["prod"]
        - name: "okta-client-secret"
          version_labels: ["prod", "stage"]
        - name: "github-webhook-secret"
          version_labels: ["prod"]
      
      ssl:
        - name: "zena-ssl-key"
          version_labels: ["prod"]
        - name: "internal-cert-key"
          version_labels: ["prod"]
      
      databases:
        - name: "lake-zena-credentials"
          version_labels: ["prod", "stage"]
        - name: "vision-lake-access"
          version_labels: ["prod"]

  key_management:
    keyring_name: "zena-keyring"
    location: "us-west4"
    keys:
      - name: "data-encryption-key"
        purpose: "ENCRYPT_DECRYPT"
        rotation_period: "7776000s"  # 90 days
      - name: "token-signing-key"
        purpose: "ASYMMETRIC_SIGN"
        rotation_period: "15552000s"  # 180 days
    
    protection_level: "HSM"
    algorithm: "GOOGLE_SYMMETRIC_ENCRYPTION"

  vault_integration:
    address: "https://vault.coaching2100.com"
    auth_method: "gcp"
    roles:
      - name: "zena-app"
        policies: ["zena-read", "zena-write"]
      - name: "claude-service"
        policies: ["claude-read"]
    
    dynamic_secrets:
      - path: "database/creds/zena"
        ttl: "1h"
      - path: "aws/creds/zena"
        ttl: "30m"

  secret_rotation:
    automated:
      enabled: true
      schedule: "0 0 * * 0"  # Weekly
      notification:
        channels: ["email", "slack"]
        recipients: ["security@coaching2100.com"]
    
    policies:
      api_keys:
        max_age: "90d"
        warning_threshold: "75d"
      certificates:
        max_age: "365d"
        warning_threshold: "30d"
      credentials:
        max_age: "180d"
        warning_threshold: "15d"

  access_control:
    audit_logging:
      enabled: true
      retention: "365d"
    
    iam_roles:
      - role: "roles/secretmanager.secretAccessor"
        members:
          - "serviceAccount:claude-service@api-for-warp-drive.iam"
          - "serviceAccount:zena-app@api-for-warp-drive.iam"
      - role: "roles/secretmanager.admin"
        members:
          - "group:security-admins@coaching2100.com"

  monitoring:
    alerts:
      - name: "secret-access"
        condition: "count > 100 per 5m"
        notification_channels: ["security-team"]
      - name: "rotation-failed"
        condition: "status = 'failed'"
        notification_channels: ["security-team", "devops-oncall"]
    
    metrics:
      - name: "secret_access_count"
        type: "counter"
        labels: ["secret_id", "service"]
      - name: "rotation_success_rate"
        type: "gauge"
        threshold: 0.99