security_config:
  encryption:
    standard: 16bit
    quantum_protection: enabled
    key_rotation:
      frequency: weekly
      automatic: true
    data_at_rest:
      encryption: enabled
      key_management: cloud_kms
    data_in_transit:
      encryption: enabled
      protocol: tls_1_3

  access_control:
    authentication:
      multi_factor: required
      session_duration: 8h
      failed_attempts_limit: 3
    authorization:
      model: role_based
      least_privilege: enforced
      roles:
        - admin
        - developer
        - analyst
        - auditor
    service_accounts:
      rotation: automated
      key_expiry: 90d

  monitoring:
    real_time:
      enabled: true
      metrics:
        - security_events
        - access_patterns
        - performance_indicators
    alerts:
      priority_levels:
        - critical
        - high
        - medium
        - low
      notification_channels:
        - email
        - slack
        - pagerduty

  compliance:
    audit_logging:
      enabled: true
      retention: 365d
      export: true
    regulatory_standards:
      - SOC2
      - HIPAA
      - GDPR
    reviews:
      frequency: quarterly
      automated_checks: enabled

  network_security:
    firewall:
      enabled: true
      rules:
        - name: allow_internal
          priority: 1000
          direction: INGRESS
        - name: deny_external
          priority: 2000
          direction: INGRESS
    vpc:
      network_isolation: enabled
      private_google_access: enabled
    cloud_nat:
      enabled: true
      redundancy: automatic

  disaster_recovery:
    backup:
      frequency: daily
      retention: 30d
      type: incremental
    failover:
      automated: true
      recovery_time_objective: 4h
      testing:
        frequency: monthly
        automated: true